spring:
  application:
    name: notification-service

---

spring:
  config:
    activate:
      on-profile:
        - default
        - local
  data:
    redis:
      port: 6379
      host: 127.0.0.1

de:
  flapdoodle:
    mongodb:
      embedded:
        version: 4.0.2

logging:
  level:
    root: debug
